const fieldLabels = {
  actions: "操作",
  receptionDate: "招待日期",
  counterparty: "招待对象",
  department: "报销部门",
  handlerName: "经手人",
  hospitalityType: "接待类型",
  location: "地点",
  invoiceDate: "发票日期",
  invoiceNumberString: "发票号",
  invoiceAmount: " 发票金额（元）",
  totalAmount: "总接待金额（含酒水）",
  theirCount: " 来访人数",
  ourCount: "我方人数",
  totalCount: "合计人数",
  perCapitaAmount: "人均金额",
  ourHostPosition: "我方主持人员职务",
  theirHostPosition: "对方主持人员职务",
  deptHeadApprovalDate: "部门负责人审批日期",
  partySecretaryApprovalDate: " 党总支书记（分管领导）审批日期",
  itemName: "物品名称",
  unitPrice: "物品单价(元)",
  quantity: "物品数量",
  lineTotal: "物品总价(元)",
  items: "购买物品明细",
};

export default fieldLabels;
